### ISSUE TITLE
Box-sizing

### ISSUE THREAD

**Issue by viirre** [adaptivemedia/adaptive-toolbox#2]
Hittar ingen generell box-sizing:

```css
* {
  box-sizing: border-box;
}
````

Annars får element fel bredd om de har padding + 100% t.ex.. 

Det bör väl ligga i ngn base typ kanske?
